### ISSUE TITLE
RxDatabase delete is not working

### ISSUE THREAD

**Issue by mkodekar** [erickok/RxCupboard#10]
```
            if (pos == 0) {
                if (contactViewholder.caImageView != null) {
                    AnimativeViews animativeViews = new AnimativeViews(context);
                    animativeViews.grow(contactViewholder.caImageView);
                    RxView.clicks(contactViewholder.caImageView).subscribe(aVoid -> {
                        contactViewholder.contactEd.getText().clear();
                        contactViewholder.mobileEd.getText().clear();
                        contactViewholder.emailEd.getText().clear();
                        contactViewholder.telephoneEd.getText().clear();
                        rxCup.delete(contactDb);
                        animativeViews.shrink(contactViewholder.caImageView);
                        rxCup.delete(CustomerContactDb.class, contactDb.getContactId());
                        Observable.just(pos).map(integer -> contactDb).subscribe(rxCup.delete());
                    });
                }
            }
```

this is my code and i see that  when i call rxdatabase.detele with the entity in it the corresponding rom does not get deleted

**Comment by erickok** [comment]
You are subscribing to a new observable inside an observable. That doesn't work. Also, you are calling delete without subscribing, so the action will not be performed. Your code looks, cleaned up, like this:

```
RxView.clicks(...).subscribe(aVoid -> {
    ...
    rxCup.delete(contactDb);
    ...
    rxCup.delete(CustomerContactDb.class, contactDb.getContactId());
    Observable.just(pos).map(integer -> contactDb).subscribe(rxCup.delete());
});
```

It is confusing for me what you like to do. For example, you are mapping the pos (list position?) to `contactDb`, which is a local model object field or something?

Assuming that `contactDb` is a variable of the type `CustumnerContactDb` the following are effectively the same:

```
rxCup.delete(contactDb);
rxCup.delete(CustomerContactDb.class, contactDb.getContactId());
```

but both of them will not do anything as you haven't subscribed yet to these observables. 

I think this is what you are trying to achieve (though I have to guess):

```
RxView.clicks(contactViewholder.caImageView)
    .map(click -> contactDb)
    .doOnNext(contact -> rxCup.delete())
    .subscribe(deletedContact -> {
        contactViewholder.contactEd.getText().clear();
        contactViewholder.mobileEd.getText().clear();
        contactViewholder.emailEd.getText().clear();
        contactViewholder.telephoneEd.getText().clear();
        animativeViews.shrink(contactViewholder.caImageView);
});
```

**Comment by mkodekar** [comment]
so you mean to set i should not create another subscribtion inside a one subscription
let me see if it works that way i will let you know

**Comment by mkodekar** [comment]
not deleting  with simple query

```
        for (ProductCategoryDb product : productcats) {
            rxDatabase.delete(product);
            L.toast(context, product.getCategoryName());
        }
```

**Comment by erickok** [comment]
Because you still do not subscribe there. If you want to delete all products in your `productcats` list, do:

```
Observable.from(productcats)
    .map(product -> rxDatabase.deleteRx()
    .subscribe(L.toast(context, "All products deleted");
```

In general remember that an Observable does nothing at all until you subscribe. (And you should not create new subscriptions inside another observable chain, like you did in the original code.)

**Comment by mkodekar** [comment]
as per your documentation i thought deleting was easy like jus 
rxDatabase.delete()

silly me

**Comment by erickok** [comment]
~~You are right! Silly me, in fact, for having incorrect documentation. I will update the doc because it is wrong! Thanks for your help.~~

**Comment by erickok** [comment]
Ok so sorry for the confusion. The doc is actually right. It depends a bit on what you supply.

```
rxDatabase.delete(someobject);
```

will work because you delete some concrete object and it is not an observable. However

```
rxDatabase.deleteRx(someobject);
```

will not work since this is an observable (`Observable<T>`) so you would need to subscribe.

```
rxDatabase.delete();
```

does not work either of course since you do not supply any object to delete. You need to use it as an action like for example

```
Observable.from(productcats)
    .subscribe(rxDatabase.delete());
```

So when I said that

```
for (ProductCategoryDb product : productcats) {
    rxDatabase.delete(product);
    L.toast(context, product.getCategoryName());
}
```

doesn't work, I was mistaken, it should work (even though I would do it via the deleteRx method like I have shown above). Just make sure that this code is not inside same other observable chain.

**Comment by mkodekar** [comment]
[reopen this issue the result is still the same here is he code

public void addProductCategory(boolean clearprvious) {
        SQLiteDatabase sqLiteDatabase = SqliteHelper.getConnection(context);
        RxDatabase rxDatabase = RxCupboard.withDefault(sqLiteDatabase);
        if (clearprvious) {
            ArrayList<ProductCategoryDb> productCategoryDbArrayList = new ArrayList<>();
            rxDatabase.query(ProductCategoryDb.class).subscribe(productCategoryDbArrayList::add);
            rxDatabase.delete(ProductCategoryDb.class);
            L.m("This is running");
        }

        ArrayList<ProductCategoryDb> productCategoryDbs = new ArrayList<>();
        ProductCategoryDb productCategoryDb = ProductCategoryDb.builder()
                .productCatId(1).productCatName("Fruits").build();
        ProductCategoryDb productCategoryDb1 = ProductCategoryDb.builder()
                .productCatId(2).productCatName("Vegetables").build();
        ProductCategoryDb productCategoryDb2 = ProductCategoryDb.builder()
                .productCatId(3).productCatName("Beverages").build();
        ProductCategoryDb productCategoryDb3 = ProductCategoryDb.builder()
                .productCatId(4).productCatName("Drinks").build();
        productCategoryDbs.add(productCategoryDb);
        productCategoryDbs.add(productCategoryDb1);
        productCategoryDbs.add(productCategoryDb2);
        productCategoryDbs.add(productCategoryDb3);
        Observable.just(productCategoryDbs).concatMap(Observable::from).subscribe(rxDatabase::put);
    }](url)

**Comment by mkodekar** [comment]
```
result is still the same reopen the issuse , i fear the delete statement is not working 

public void addProductCategory(boolean clearprvious) {
        SQLiteDatabase sqLiteDatabase = SqliteHelper.getConnection(context);
        RxDatabase rxDatabase = RxCupboard.withDefault(sqLiteDatabase);
        if (clearprvious) {
            ArrayList<ProductCategoryDb> productCategoryDbArrayList = new ArrayList<>();
            rxDatabase.query(ProductCategoryDb.class).subscribe(productCategoryDbArrayList::add);
            rxDatabase.delete(ProductCategoryDb.class);
            L.m("This is running");
        }

        ArrayList<ProductCategoryDb> productCategoryDbs = new ArrayList<>();
        ProductCategoryDb productCategoryDb = ProductCategoryDb.builder()
                .productCatId(1).productCatName("Fruits").build();
        ProductCategoryDb productCategoryDb1 = ProductCategoryDb.builder()
                .productCatId(2).productCatName("Vegetables").build();
        ProductCategoryDb productCategoryDb2 = ProductCategoryDb.builder()
                .productCatId(3).productCatName("Beverages").build();
        ProductCategoryDb productCategoryDb3 = ProductCategoryDb.builder()
                .productCatId(4).productCatName("Drinks").build();
        productCategoryDbs.add(productCategoryDb);
        productCategoryDbs.add(productCategoryDb1);
        productCategoryDbs.add(productCategoryDb2);
        productCategoryDbs.add(productCategoryDb3);
        Observable.just(productCategoryDbs).concatMap(Observable::from).subscribe(rxDatabase::put);
    }
```

**Comment by mkodekar** [comment]
and i did this as well

```
Observable.from(productcats)
    .subscribe(rxDatabase.delete());
```

**Comment by erickok** [comment]
```
 rxDatabase.delete(ProductCategoryDb.class);
```

What do you expect should happen here? You are supplying a class but no id of the object to remove. Either give the actual object instance or use the class + the id.

```
 rxDatabase.delete(someProductCategoryDbObject); // Would remove a specific product category
 rxDatabase.delete(ProductCategoryDb.class, 10L); // Would remove product category with id 10
```

**Comment by mkodekar** [comment]
The i want to delete all not a want to keep a single one of them irrespective of the id

**Comment by erickok** [comment]
I see. I do not actually expose any such method. I should add it. In the meantime you can use Cupboard directly to do that:

```
DatabaseComparment dc = cupboard().withDatabase(SqliteHelper.getConnection(context));
dc.delete(ProductCategoryDb.class, "");
```

Of course that would mean that RxCupboard cannot propagate change events for this, but perhaps you are not using this anyway.
