### ISSUE TITLE
@column  @Ignore invalid

### ISSUE THREAD

**Issue by NullCrazy** [erickok/RxCupboard#12]
public class Item {
    public Long _id;
    @Column("test")
    public String title;
    @Ignore
    public Integer index;

    @Override
    public String toString() {
        return title;
    }
}
create table column “index” existence，column name is called ”title”, not ”test”。。

**Comment by NullCrazy** [comment]
I set the column as 'test' but it's still 'title' in real table

**Comment by erickok** [comment]
Even if this is an issue, it is an issue in the core Cupboard library (cf https://bitbucket.org/littlerobots/cupboard) and not RxCupboard. Check your imports, you might not have the right Column annotation.
