### ISSUE TITLE
dependency nl.2312:rxcupboard:0.2 missing classes

### ISSUE THREAD

**Issue by nodinosaur** [erickok/RxCupboard#2]
Updating the [sample app](https://github.com/erickok/RxCupboard/blob/509974783cbf288c6f631c3ccebd565299037ce4/sample/build.gradle) to use the dependency stated in the [README](https://github.com/erickok/RxCupboard/blob/bd576f8d5ad568dda39e8673522ecc04d0497e2b/README.md) to

`dependencies {`
`compile 'nl.2312:rxcupboard:0.2'`
`compile 'io.reactivex:rxandroid-framework:0.24.0'`
`}`

Throws the following import error

`import nl.nl2312.rxcupboard.OnDatabaseChange;`

Reviewing `classes.jar` we can see:
![classes](https://cloud.githubusercontent.com/assets/2144571/7440748/eb7ef254-f0bd-11e4-953c-188e7fa58580.png)

**Comment by erickok** [comment]
The released version of RxCupboard is version 0.2 while the sample you are trying to compile is slightly newer and indeed is supposed to be compiled again the master branch version which DOES have the OnDatabaseChange class. In other words, you are compiling against an incorrect version.

**Comment by nodinosaur** [comment]
In this case, I would presume the relevant sample application to be on the same branch as the _feature_ branch? And the Master branch should contain a sample compatible with the advertised release?

**Comment by erickok** [comment]
You expect the master branch to be the same as the latest release, but this is not the case. The master branch is the latest stable code, but might not yet have been released (as currently the case). I agree it is a bit more intuitive if master would contain the latest release. I will make this so after the next release.

**Comment by nodinosaur** [comment]
Thanks for creating this lib, it really is nice & simple to use.
