### ISSUE TITLE
Close database cursors properly

### ISSUE THREAD

**Issue by realdadfish** [erickok/RxCupboard#7]
Right now the usage of RxCupboard leads to StrictMode warnings about unclosed cursors. Since the library abstracts away the underlying `QueryResultIterable` on which one could call `close()` manually, this needs to be patched in the library itself.

Discussion: https://plus.google.com/u/0/+ThomasKeller1/posts/6ecnnGaru1U

**Comment by realdadfish** [comment]
Apparently 0.7 was released, but I don't see it yet in the repos. Anything stopping the upload?

**Comment by erickok** [comment]
My bad; I hit the wrong button. Re-published to Maven, so available very soon!

**Comment by mkodekar** [comment]
How to get Cursor by the way  with this library

**Comment by erickok** [comment]
@mkodekar Do you mean how to wrap a cursor with this library or how-to grab a Cupboard database cursor?

**Comment by mkodekar** [comment]
nevermind i got it myself , actually there are some things i also wanted to ask was how can i denote a partiucal coloumn to have a primary key as well as deleting an identical row , this is budging me since long.

**Comment by erickok** [comment]
@mkodekar Please open a new issue if you have any question, as not to clutter this solved issue, please. As for cupboard-specific issues, please ask at https://plus.google.com/u/0/communities/102678039256081927502 In Cupboard there is only one field to be the primary key, the `_id`.
